### PR TITLE
Add xmpp-ftw

### PR DESCRIPTION
**Pull request by lloydwatkin**

### CODE REVIEW

**Comment by jbinary** [comment]
Don't like when bundles or minimized js is pushed to a git repo. Why are they needed here? I prefer to provide build instructions and/or makefiles instead of this.

**Comment by lloydwatkin** [comment]
@jbinary just following the existing pattern that @fippo and @legastero are using. I understand what you mean but as this is for demos I'd imagine a majority of people would want to just download the code and have it work straight away - and then possibly investigate further later on.

If you want to see the non-compressed version I have it in a repo here: https://github.com/xmpp-ftw/webrtc-demo.

**Comment by fippo** [comment]
@legastero: can you give @lloydwatkin commits rights please?

**Comment by fippo** [comment]
I'd note that as a policy decision it would be useful not to compress your jingle code. That makes debugging alot easier and that's the primary goal of this repo. :-)

**Comment by lloydwatkin** [comment]
Non-compressed version was part of the pull request, but it is bundled as @jbinary pointed out.  @fippo's suggestion of a `readme.md` pointing to the full repos for each project (not suggested here) is a good idea I think.

**Comment by jbinary** [comment]
Yeah, I am a supporter of the idea of separation. I don't see any necessity of storing any compiled sources in the repo because it puts additional requirements on updating them and may broke commits atomicity. So if you want to do builds to make user's lives easier (what's actually the best desire), do it separately from the working repo.

Sorry, if my comment is not really relevant, I haven't got familiar with the repos enough yet. :)

**Comment by fippo** [comment]
just changed the README.md accordingly.

**Pull request merged**
